title: Hello, world! I'm Gaurav Sharma
description: > # this means to ignore newlines until "baseurl:"
  This is my personal blog containing all things Deep Learning. Here you can find posts on explanation of popular research papers, recent advancements, my observations and detailed description of my projects.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Gaurav Sharma # add your name
author-img: gaurav-shar.jpg # add your photo
about-author: I am a deep learning enthusiast with a knack for Computer Vision. # add description
# social-twitter: # add your Twitter handle
# social-facebook: # add your Facebook handle
social-github: gaushh # add your Github handle
social-linkedin: gauravsharmajpr # add your Linkedin handle
social-email: gsharma14497@gamil.com #add your Email address

# Disqus
discus-identifier: gaushh # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
